### PR TITLE
release-1.6.8

### PR DESCRIPTION
**Pull request by SharonManrique**

### CODE REVIEW

**Comment by SharonManrique** [comment]
✔ develop hash: 2184af9c9a8f47beeca06041df383da5d136d22d493b52e656114cb1e8ff6a42
✔ prod hash:    2184af9c9a8f47beeca06041df383da5d136d22d493b52e656114cb1e8ff6a42
✔ Hashes are a match!

**Comment by Mrtenz** [comment]
```
✔ develop hash: 2184af9c9a8f47beeca06041df383da5d136d22d493b52e656114cb1e8ff6a42
✔ prod hash:    2184af9c9a8f47beeca06041df383da5d136d22d493b52e656114cb1e8ff6a42
✔ Hashes are a match!
```

**Comment by SharonManrique** [comment]
https://mycryptohq.slack.com/archives/CKJ2NCGA3/p1560456886033300

**Comment by blurpesec** [comment]
```
✔ develop hash: 2184af9c9a8f47beeca06041df383da5d136d22d493b52e656114cb1e8ff6a42
✔ prod hash:    2184af9c9a8f47beeca06041df383da5d136d22d493b52e656114cb1e8ff6a42
✔ Hashes are a match!
```

**Pull request merged**
