### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by ConnorBryan**

### CODE REVIEW

**Comment by ConnorBryan** [comment]
✔ develop hash:	b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ prod hash:	b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ Hashes are a match!

**Comment by nickserv** [comment]
✔ develop hash:	b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ prod hash:	b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ Hashes are a match!

**Comment by SharonManrique** [comment]
✔ develop hash: b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ prod hash:    b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ Hashes are a match!

**Comment by data-go** [comment]
✔ develop hash:	b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ prod hash:	b9f0ca3f646f8d7055a9914c09dff59501c4c970dd798bdffd0f21c74528e365
✔ Hashes are a match!

**Pull request merged**
