### PR TITLE
Release 1.4.2.1

### PR DESCRIPTION
**Pull request by ConnorBryan**

### CODE REVIEW

**Comment by ConnorBryan** [comment]
```
✔ develop hash:	c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ prod hash:	c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ Hashes are a match!
```

**Comment by SharonManrique** [comment]
✔ develop hash: c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ prod hash:    c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec

**Comment by nickserv** [comment]
```
✔ develop hash:	c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ prod hash:	c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ Hashes are a match!
```

**Comment by data-go** [comment]
✔ develop hash:	c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ prod hash:	c21454337fd1fe2891194b3fb4f340a9faa2bbad52083030dd09e9285e7b17ec
✔ Hashes are a match!

**Pull request merged**
