### PR TITLE
Release 1.5.2

### PR DESCRIPTION
**Pull request by ConnorBryan**

### CODE REVIEW

**Comment by ConnorBryan** [comment]
```
✔ develop hash:	b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ prod hash:	b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ Hashes are a match!
```

**Comment by shazzabazza** [comment]
✔ develop hash: b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ prod hash:    b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ Hashes are a match!

**Comment by SharonManrique** [comment]
✔ develop hash:	b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ prod hash:	b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ Hashes are a match!

**Comment by tayvano** [comment]
✔ develop hash:	b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ prod hash:	b38e852c2a93b34f2df4693736479f47309b205acd8e555984d197e113c2e943
✔ Hashes are a match!

**Pull request merged**
