### PR TITLE
release-1-6-0

### PR DESCRIPTION
**Pull request by SharonManrique**
- gas price bug hot fix
- Trezor update
- CSP

### CODE REVIEW

**Comment by SharonManrique** [comment]
✔ develop hash: 2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ prod hash:    2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ Hashes are a match!

**Comment by nickserv** [comment]
```
✔ develop hash:	2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ prod hash:	2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ Hashes are a match!
```

**Comment by data-go** [comment]
✔ develop hash:    2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ prod hash:    2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ Hashes are a match!

**Comment by blurpesec** [comment]
```

**Comment by blurpesec** [comment]
```

**Comment by blurpesec** [comment]
```
✔ develop hash: 2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ prod hash:    2bb6a137a2e0f4242d8d8b7ab2c13948debc144a0ac6d154afa047f3d590e5b6
✔ Hashes are a match!
```

**Review by data-go — APPROVED** [review]

**Pull request merged**
