### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by ConnorBryan**

### CODE REVIEW

**Comment by SharonManrique** [comment]
✔ develop hash: c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ prod hash:    c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a

**Comment by ConnorBryan** [comment]
✔ develop hash:	c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ prod hash:	c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ Hashes are a match!

**Comment by nickserv** [comment]
✔ develop hash:    c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ prod hash:    c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ Hashes are a match!

**Comment by data-go** [comment]
✔ develop hash:	c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ prod hash:	c9292d784c3cb060686aff791baa1245aec9bd978846da229f2a960b3f8b386a
✔ Hashes are a match!

**Pull request merged**
