### PR TITLE
release-1-6-1-c

### PR DESCRIPTION
**Pull request by tayvano**

### CODE REVIEW

**Comment by blurpesec** [comment]
```
✔ develop hash: d8e78593ad2610abf9c59aa219398d6d1919a571a12f575b8e642328ad35436f
✔ prod hash:    d8e78593ad2610abf9c59aa219398d6d1919a571a12f575b8e642328ad35436f
✔ Hashes are a match!
```

**Comment by SharonManrique** [comment]
✔ develop hash: d8e78593ad2610abf9c59aa219398d6d1919a571a12f575b8e642328ad35436f
✔ prod hash:    d8e78593ad2610abf9c59aa219398d6d1919a571a12f575b8e642328ad35436f
✔ Hashes are a match!

**Comment by data-go** [comment]
```
✔ develop hash:	d8e78593ad2610abf9c59aa219398d6d1919a571a12f575b8e642328ad35436f
✔ prod hash:	d8e78593ad2610abf9c59aa219398d6d1919a571a12f575b8e642328ad35436f
✔ Hashes are a match!
```

**Review by data-go — APPROVED** [review]

**Comment by SharonManrique** [comment]
Official release 1.6.1

**Pull request merged**
