### PR TITLE
release-1-7-3

### PR DESCRIPTION
**Pull request by wtzb**

### CODE REVIEW

**Comment by wtzb** [comment]
https://mycryptohq.slack.com/archives/CKJ2NCGA3/p1571337925002300

**Comment by wtzb** [comment]
```
✔ develop hash: 2b0869bde2dc175aa185ebcfd353d13191e0911fd6b5a5f85367c53643bcc813
✔ prod hash:    2b0869bde2dc175aa185ebcfd353d13191e0911fd6b5a5f85367c53643bcc813
✔ Hashes are a match!
```

**Comment by blurpesec** [comment]
```
✔ develop hash: 2b0869bde2dc175aa185ebcfd353d13191e0911fd6b5a5f85367c53643bcc813
✔ prod hash:    2b0869bde2dc175aa185ebcfd353d13191e0911fd6b5a5f85367c53643bcc813
✔ Hashes are a match!
```

**Comment by Mrtenz** [comment]
```
✔ develop hash: 2b0869bde2dc175aa185ebcfd353d13191e0911fd6b5a5f85367c53643bcc813
✔ prod hash:    2b0869bde2dc175aa185ebcfd353d13191e0911fd6b5a5f85367c53643bcc813
✔ Hashes are a match!
```

**Pull request merged**
