### PR TITLE
Release 1.3.1

### PR DESCRIPTION
**Pull request by ConnorBryan**

### CODE REVIEW

**Comment by ConnorBryan** [comment]
From commit: `ce8e004e782a2fe1fcacecda36aa0223a733215a`
To commit: `b684795ba71c577f15c378a8eeb6c5e902918b75`

**Comment by SharonManrique** [comment]
✔ develop hash: 5db56672e2d2c4dd86ddee0acf78540e542c5375d6ac2a1a0bbe0da2a264daa1
✔ prod hash:    5db56672e2d2c4dd86ddee0acf78540e542c5375d6ac2a1a0bbe0da2a264daa1

**Comment by ConnorBryan** [comment]
✔ develop hash:	5db56672e2d2c4dd86ddee0acf78540e542c5375d6ac2a1a0bbe0da2a264daa1
✔ prod hash:	5db56672e2d2c4dd86ddee0acf78540e542c5375d6ac2a1a0bbe0da2a264daa1

**Comment by nickserv** [comment]
✔ develop hash: 5db56672e2d2c4dd86ddee0acf78540e542c5375d6ac2a1a0bbe0da2a264daa1
✔ prod hash:    5db56672e2d2c4dd86ddee0acf78540e542c5375d6ac2a1a0bbe0da2a264daa1

**Pull request merged**
